<?php

namespace AppBundle\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends \Doctrine\ORM\EntityRepository
{

    public function nbrClients()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = ' 
                SELECT COUNT(id) as nbrclients FROM `clients`
            ';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

}
