<?php

namespace AppBundle\Repository;

/**
 * LentileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LentileRepository extends \Doctrine\ORM\EntityRepository
{
}
