<?php

namespace AppBundle\Repository;

/**
 * stockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockRepository extends \Doctrine\ORM\EntityRepository
{
    public function misajourqantite($refproduit)
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.refproduit = :refprod')
            ->set('u.qantite','u.qantite - 1')
            ->setParameter('refprod', $refproduit)
            ->update('AppBundle\Entity\Stock', 'u')
            ->getQuery()
            ->execute();
    }

}
