app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

my_route_to_expose:
    path:     /admin/statistique/caisse
    defaults: { _controller: AppBundle:Statistique:todaycaissetotal }
    options:
        expose: true
